### PR TITLE
Create News,-blogs,-videos-and-articles.md

### PR DESCRIPTION
**Pull request by EricJWHuang**
Add a new article about using PactNET

### CODE REVIEW

**Comment by mboudreau** [comment]
Thanks for your contribution :)

**Comment by mboudreau** [comment]
@EricJWHuang sorry, could you please do this again, but on the master branch, not the test one.

Thanks.

**Comment by EricHuang-AGL** [comment]
@mboudreau Sure Michel but which folder should I upload to?

image

**Comment by mboudreau** [comment]
I think it should go under _docs with the title of 'Articles & News'.
Please refer to other MD files under that folder for the structure.

Thanks :)

**Comment by uglyog** [comment]
This needs to be on the test branch to be published in the gitbook at docs.pact.io.

**Comment by mboudreau** [comment]
I've added it to both.

**Pull request merged**
