### PR TITLE
fix Pact.like example documentation, add example

### PR DESCRIPTION
**Pull request by mycargus**
fixes https://github.com/realestate-com-au/pact/issues/120

### CODE REVIEW

**Comment by mefellows** [comment]
thanks @mycargus !

**Comment by uglyog** [comment]
I'll copy the contents to the realestate-com-au/pact wiki

**Comment by bethesque** [comment]
@uglyog done that thanks.

**Comment by ipai84** [comment]
Thanks @mycargus!!

**Pull request merged**
